name: Laravel Pint Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pint:
    name: Run Laravel Pint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          ini-values: post_max_size=256M
          tools: composer
          coverage: none

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Run Laravel Pint (dry-run)
        id: pint
        run: vendor/bin/pint --test --verbose
